const js = require('@eslint/js');
const globals = require('globals');

// All scripts share the window scope (no module bundler). Globals declared here
// prevent false no-undef positives for names defined in other script files.
const crossModuleGlobals = {
  // config.js — constants
  MODEL_NAME: 'readonly',
  VISION_MODEL_NAME: 'readonly',
  OLLAMA_API_URL: 'readonly',
  OLLAMA_TAGS_URL: 'readonly',
  OLLAMA_MODEL_KEY: 'readonly',
  SETTINGS_API_URL: 'readonly',
  CONVERSATIONS_API_URL: 'readonly',
  VOICEBOX_SPEAK_URL: 'readonly',
  PIPER_SPEAK_URL: 'readonly',
  DOC_EXTRACT_URL: 'readonly',
  OLLAMA_NUM_CTX: 'readonly',
  MAX_HISTORY_MESSAGES: 'readonly',
  MAX_INPUT_LENGTH: 'readonly',
  MAX_UPLOAD_FILE_BYTES: 'readonly',
  MAX_IMAGE_SIZE_BYTES: 'readonly',
  MAX_DOCUMENT_UPLOAD_BYTES: 'readonly',
  MAX_DOCUMENT_TEXT_CHARS: 'readonly',
  SILENCE_TIMEOUT_MS: 'readonly',
  CHAR_COUNTER_SHOW_THRESHOLD: 'readonly',
  CHAR_COUNTER_WARNING_THRESHOLD: 'readonly',
  CHAR_COUNTER_DANGER_THRESHOLD: 'readonly',
  SPEECH_RECOGNITION_LANG: 'readonly',
  PERSONA_PREFS_KEY: 'readonly',
  EDITOR_MODE_KEY: 'readonly',
  NAV_RAIL_KEY: 'readonly',
  SIDEBAR_STATE_KEY: 'readonly',
  systemPrompts: 'readonly',
  personaLabels: 'readonly',
  // config.js — mutable state
  conversationHistory: 'writable',
  currentSystemPrompt: 'writable',
  currentModel: 'writable',
  currentVisionModel: 'writable',
  vpalSettings: 'writable',
  pendingImageDataUrl: 'writable',
  pendingImageBase64: 'writable',
  currentThinkingMode: 'writable',
  currentTTSEngine: 'writable',
  currentEditorMode: 'writable',
  currentNavRailEnabled: 'writable',
  pendingDocumentText: 'writable',
  pendingDocumentName: 'writable',
  pendingDocumentTruncated: 'writable',
  // utils.js
  formatTimestamp: 'readonly',
  escapeHtml: 'readonly',
  showToast: 'readonly',
  splitThinkingContent: 'readonly',
  calcResizeDims: 'readonly',
  detectVisionContext: 'readonly',
  stripMarkdownForSpeech: 'readonly',
  protectLatexDelimiters: 'readonly',
  restoreLatexBackslashes: 'readonly',
  truncateDocumentText: 'readonly',
  buildDocumentMessageContent: 'readonly',
  parseDocumentMessageContent: 'readonly',
  diffWords: 'readonly',
  parseOllamaModels: 'readonly',
  // speech.js — functions
  toggleSpeechRecognition: 'readonly',
  speakText: 'readonly',
  stopSpeaking: 'readonly',
  // speech.js — mutable state accessed cross-module
  recognition: 'readonly',
  isRecording: 'writable',
  silenceTimer: 'writable',
  accumulatedTranscript: 'writable',
  isSpeaking: 'writable',
  // chat.js — SVG icon strings referenced by speech.js button state updates
  COPY_ICON: 'readonly',
  CHECK_ICON: 'readonly',
  SPEAK_ICON: 'readonly',
  STOP_ICON: 'readonly',
  SPINNER_ICON: 'readonly',
  REGEN_ICON: 'readonly',
  EDIT_ICON: 'readonly',
  // chat.js — functions
  updateSystemPromptState: 'readonly',
  addUserMessage: 'readonly',
  addAIMessagePlaceholder: 'readonly',
  addContextTrimNotice: 'readonly',
  clearChat: 'readonly',
  closeWindow: 'readonly',
  sendMessage: 'readonly',
  sendMessageAndContinueListening: 'readonly',
  saveChat: 'readonly',
  openChat: 'readonly',
  renderConversationHistory: 'readonly',
  handleOpenFile: 'readonly',
  renderMathIn: 'readonly',
  highlightCodeIn: 'readonly',
  renderMermaidIn: 'readonly',
  enrichRenderedContent: 'readonly',
  renderMarkdownToHtml: 'readonly',
  _resolveSystemPrompt: 'readonly',
  _currentPersonaKey: 'readonly',
  renderEditorReply: 'readonly',
  _buildEditorViewSwitch: 'readonly',
  regenerateLastResponse: 'readonly',
  editLastUserTurn: 'readonly',
  _refreshTurnControls: 'readonly',
  _lastExchangeIndices: 'readonly',
  _editableTextFor: 'readonly',
  _streamInProgress: 'readonly',
  _dispatchSend: 'readonly',
  _makeTurnControl: 'readonly',
  // main.js
  clearImagePreview: 'readonly',
  clearDocumentPreview: 'readonly',
  _defaultVpalSettings: 'readonly',
  _migrateLegacySettingsIfNeeded: 'readonly',
  // settings.js
  initSettings: 'readonly',
  openSettings: 'readonly',
  closeSettings: 'readonly',
  applyResolvedSettings: 'readonly',
  resolveSetting: 'readonly',
  resolveThinkingMode: 'readonly',
  resolveTtsEngine: 'readonly',
  diffSettings: 'readonly',
  buildMigrationPayload: 'readonly',
  // api.js
  streamOllamaResponse: 'readonly',
  stopStreaming: 'readonly',
  // nav-rail.js
  initNavRail: 'readonly',
  setNavRailEnabled: 'readonly',
  navRailCollapseTitle: 'readonly',
  navRailTruncateWords: 'readonly',
  navRailBuildModel: 'readonly',
  // history.js
  initHistory: 'readonly',
  hcNewChat: 'readonly',
  hcRefreshSidebar: 'readonly',
  hcCurrentId: 'readonly',
  hcNewConversationId: 'readonly',
  hcArchiveCurrent: 'readonly',
  hcTouchCurrent: 'readonly',
  hcLoadConversation: 'readonly',
  hcBeaconSave: 'readonly',
  chatTitleFrom: 'readonly',
  conversationRecordFrom: 'readonly',
  filterConversations: 'readonly',
  resolveActiveCardId: 'readonly',
  // main.js
  closeSidebarDrawer: 'readonly',
  // vendored libraries (loaded before app scripts)
  marked: 'readonly',
  DOMPurify: 'readonly',
  renderMathInElement: 'readonly',
  diff_match_patch: 'readonly',
  hljs: 'readonly',
  mermaid: 'readonly',
};

module.exports = [
  // Global ignore — never lint vendored third-party files regardless of how
  // ESLint is invoked (glob or directory). A standalone ignores block without
  // `files` applies globally in ESLint v9 flat config. diff-match-patch.js is
  // Google's official uncompressed build, vendored verbatim (see index.html /
  // CLAUDE.md "Updating Vendored Libraries") — it is not renamed to *.min.js.
  { ignores: ['**/*.min.js', 'src/aia/scripts/diff-match-patch.js'] },
  {
    files: ['src/aia/scripts/*.js'],
    ...js.configs.recommended,
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: 'script',
      globals: {
        ...globals.browser,
        ...crossModuleGlobals,
      },
    },
    rules: {
      // console.error / console.warn are used intentionally throughout
      'no-console': 'off',
      // Top-level names are exported to window for use by other scripts;
      // only flag unused variables that are local to a function.
      'no-unused-vars': ['error', { vars: 'local', args: 'after-used' }],
    },
  },
];
